{"name": "Логин с неверным логином или паролем", "status": "passed", "description": "Этот тест проверяет, что при неверных данных логина возвращается ошибка.", "steps": [{"name": "Отправка запроса с неправильными данными", "status": "passed", "start": 1744925093037, "stop": 1744925093678}, {"name": "Проверка, что возвращается статус-код 401", "status": "passed", "start": 1744925093679, "stop": 1744925093679}, {"name": "Проверка, что сообщение об ошибке корректно", "status": "passed", "start": 1744925093679, "stop": 1744925093679}], "parameters": [{"name": "email", "value": "''"}, {"name": "password", "value": "'correctpass'"}], "start": 1744925093037, "stop": 1744925093679, "uuid": "240fe07e-bf43-45ae-8436-6cb44ebb796f", "historyId": "ce37c0656cf6fd515598db832f5279c3", "testCaseId": "8f9cda47c51ec7bbc26bb76800a7f0aa", "fullName": "tests.test_user_login#test_login_with_invalid_credentials", "labels": [{"name": "feature", "value": "Пользователь"}, {"name": "story", "value": "Логин"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user_login"}, {"name": "host", "value": "MacBook-Pro-George.local"}, {"name": "thread", "value": "39352-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user_login"}]}